### ISSUE TITLE
Code review for package_copy

### ISSUE THREAD

**Issue by dmullen17** [NCEAS/datamgmt#10]
Code review for the three functions in R/package_copy.R would be appreciated!  Open to any general changes / comments.  
https://github.com/NCEAS/datamgmt/blob/master/R/package_copy.R

**Comment by dmullen17** [comment]
One area that might need improvement:  I didn't update `otherEntity`s or `dataTable`s in the EML as it slows down the function considerably.  Although I suppose it could added as an optional argument.

**Comment by isteves** [comment]
Will do!

**Comment by amoeba** [comment]
Hey @dmullen17 sorry I took so long to take a look. Overall, everything looked pretty good. I made some comments directly on the source using Hypothesis https://hyp.is/7G4z3graEeiK2OMAbsIW1Q/github.com/NCEAS/datamgmt/blob/master/R/package_copy.R. I'm also curious if annotating your source code that way worked well for giving this feedback.

One thing I noticed is that you can greatly simplify everything if you use the same PIDs for all the copied Objects. This requires the destination MN is in a different environment than the source MN. If you re-use all the PIDs, you can only copy once too, which is a limitation. But the code is way simpler: https://gist.github.com/amoeba/efde94a63dba40b82237d041f802719d. What do you think about that?
