### ISSUE TITLE
clone_package feature request

### ISSUE THREAD

**Issue by dmullen17** [NCEAS/datamgmt#103]
`clone_package` copies a parent + it's (optional) children.  It does not update the package metadata to reflect the new pids yet.  

Filing this issue as a feature request so I don't forget.

**Comment by maier-m** [comment]
This maybe would be best served in a new function... i.e. first clone a package then update the EML to ensure all otherEntities and dataObjects have correct physicals. Splitting into two functions would allow users to access each individually which I think would be valuable. Although this might be a fairly tough problem to match new data pids with existing EML objects.

**Comment by jagoldstein** [comment]
We can do this on a case-by-case basis.
