### ISSUE TITLE
`obsolete_package`: no error checking for token

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/datamgmt#143]
forgot to put in a token, and the result when using `obsolete_package` without one is:

obsolete_package(mn, "urn:uuid:14d91309-0ecb-4c78-88a4-ff6e691bcc9a", "urn:uuid:17d733ef-cb2b-48e0-8ca7-07aa162c6b70")
Error: arcticdatautils::object_exists(mn, metadata_obs) is not TRUE

which makes it look like there is no object there, but the issue was really the token.

**Comment by dmullen17** [comment]
good catch, that definitely needs to be added

**Comment by jeanetteclark** [comment]
otherwise works great!
