### ISSUE TITLE
Update pkgdown

### ISSUE THREAD

**Issue by isteves** [NCEAS/datamgmt#146]
The datamgmt pkgdown site is a good place for newbies to datamgmt to explore a curated list of functions, but is currently very out of date

@dmullen17 perhaps you're interested?

**Comment by drkrynstrng** [comment]
We should consider using the `tic` [package](https://ropenscilabs.github.io/tic/index.html) to automate updating the `pkgdown` site through CI, such as when changing documentation and vignettes.
