### ISSUE TITLE
create_attributes_table doesn't show table

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/datamgmt#151]
I just get a blank screen when using create_attributes_table. Sometimes this error pops up in the console:

```Warning: Error in safeFromJSON: Argument 'txt' is not a valid JSON string.
  [No stack trace available]
Error in safeFromJSON(charData, simplifyVector = FALSE) : 
  Argument 'txt' is not a valid JSON string.```

**Comment by dmullen17** [comment]
Solved for the time being.  Slackbot message for this issue: 

 ```Having trouble with the `datamgmt::create_attributes_table` function?  It's probably because your version of `httpuv` is incompatible.  Run `devtools::install_version("httpuv", "1.4.3")` and restart your R session and try running the code again.  Downgrading to version `1.4.3` usually solves the issue, however you can also try upgrading to the latest release of `httpuv`.  It's also possible that this is a browser issue - try switching your browser if this doesn't work.```
