### ISSUE TITLE
update_eml_with_new_pids function.

### ISSUE THREAD

**Issue by dmullen17** [NCEAS/datamgmt#153]
Another idea for a fellows first project / function: 

The idea here is that we sometimes use `datamgmt::clone_package` or `datamgmt::copy_package` to clone or copy a package to another member node, or to restore a previous version.  This function does not update the pids in the eml (if `new_pids = TRUE` in the case of `clone_package`).  It would be useful to write a helper function that does this in an efficient manner and add it to `copy_package` and conditionally in `clone_package` if `new_pids = TRUE`.  

Potential workflow: 
1.  Copy a package with ~10 data objects from production to test 
2.  Match the new data pids to their old pids in the EML (this could be done multiple ways, but using checksum might the most efficient)
3.  Update the EML with the new pids (physical section)

**Comment by dmullen17** [comment]
The same idea as #103

**Comment by jagoldstein** [comment]
We can do this on a case-by-case basis.
