### ISSUE TITLE
create_attributes_table textDomain bug

### ISSUE THREAD

**Issue by dmullen17** [NCEAS/datamgmt#156]
For textDomain `definition` is a required field.  Function should copy attributeDefinition into definition by default, or make definition a red box when using the shiny app.  

This bug fix should also be applied to `eml2` version of this function.

**Comment by jeanetteclark** [comment]
I wrote this in Slack but I don't think that there is a bug. Red box shows up as expected
<img width="1981" alt="screen shot 2018-07-26 at 12 25 52 pm" src="https://user-images.githubusercontent.com/24237074/43284313-44e7edea-90d0-11e8-917a-4f120619ee9d.png">

**Comment by dmullen17** [comment]
🙏
