### ISSUE TITLE
Create a QA function to check physical of object

### ISSUE THREAD

**Issue by drkrynstrng** [NCEAS/datamgmt#157]
When using `qa_package` an object may fail to process because the distribution URL in the physical is missing or differs from the object pid. It would be nice to have a helper function to pinpoint exactly what is happening with the physical. The main possibilities are that the physical is simply missing, the physical was not updated after the object was updated, or the wrong physical was assigned to the object. A `qa_physical` function would first check if the physical exists and if so check for these other possibilities to narrow down the issue, producing the appropriate messages to guide action. I'd be happy to work on this if it sounds like a good idea.

**Comment by jeanetteclark** [comment]
Sounds like a good idea to me. You could write `qa_physical` as a function in the `datamgmt` package, but not export it. I agree it would be good to have more informative messages about the physical section in the `qa_package` output. Although - the `qa_package` output is already super long, so if we can I'd like to keep it from getting TOO much longer

**Comment by dmullen17** [comment]
@drkrynstrng I added netcdf capability to `qa_package` #158, so make sure you pull those changes in to avoid merge conflicts
