### ISSUE TITLE
Automate updating pkgdown site

### ISSUE THREAD

**Issue by drkrynstrng** [NCEAS/datamgmt#173]
It is possible to automate updating of pkgdown sites through Travis builds whenever function documentation or vignettes change. This would keep the pkgdown site up to date with the latest changes in the repo.

There are at least two approaches to this automation:
https://www.datacamp.com/community/tutorials/cd-package-docs-pkgdown-travis
or, using the tic package,
https://ropenscilabs.github.io/tic/articles/tic-advantages.html#easier-deployment

**Comment by jagoldstein** [comment]
We don't use the pkgdown site

https://nceas.github.io/datamgmt
