### ISSUE TITLE
Rename the maste branch to main

### ISSUE THREAD

**Issue by csjx** [NCEAS/datamgmt#215]
From an inclusivity perspective, I suggest we rename the `master` branch to `main` and generally use more welcoming terms as we describe our software architectures. The use of the the terms `master` and `slave` in computing are not welcoming.  For context, see the [Inclusive Naming](https://inclusivenaming.org) project and [this repo](https://github.com/github/renaming).

**Comment by laijasmine** [comment]
realized I don't have access to settings for this repo. Otherwise the branches can be changed in 5 steps outlined in this post here: 
https://github.com/StevenMMortimer/master-to-main

**Comment by mbjones** [comment]
New repos are being created now with `main` as the primary branch name. GitHub also supports renaming through the web UI, which has a bunch of advantages, as outlined here: https://github.com/github/renaming

I had been waiting on that functionality to be present, but we should probably now go ahead and rename most or all of our repos, but will need to pay attention to Travis/Jenkins etc as well.

**Comment by laijasmine** [comment]
Done by Matt.

Github also prompts users who access the repo afterwards that it has been renamed and what commands to run to update itl.
