### ISSUE TITLE
Combining object updates/resource map

### ISSUE THREAD

**Issue by isteves** [NCEAS/datamgmt#43]
Currently, any time you update an object with a new version (via update_object), you have to save the new PID and then update the resource map.

I'm guessing it's possible to bundle the two together into one function, which updates the resource map whenever an object is updated.

**Comment by isteves** [comment]
@amoeba what do you think of adding this functionality to arcticdatautils?  any problems you foresee?

**Comment by amoeba** [comment]
Hey @isteves thanks for the idea! So you want to update a Data Object in a Data Package, and then update the Resource Map so it has the updated Data Object in it instead of the old one?

**Comment by isteves** [comment]
Yep, just combining the two steps (general idea below).  I guess if you update multiple datasets at once, it may be more efficient to use the current update_package function and then do only one publish_update at the end.  However, perhaps adding in an update_rm = TRUE/FALSE argument (default = TRUE) could allow for both use-cases.

_Disclaimer: I don't remember all the arguments since I'm on my personal computer w/o arcticdatautils_
update_package2 <- function(mn, rm_pid, data_pid, new_data_path) {
    pkg <- get_package(mn, rm_pid)
    new_data_pid <- update_package(mn, data_pid, data_path)
    publish_update(mn,
                   pkg$metadata,
                   pkg$resource_map,
                   c(pkg$data[-which(pkg$data %in% data_pid)], 
                     new_data_pid))
}

**Comment by amoeba** [comment]
Something like that could work. I'd like to keep `update_object` as-is since it's a simple routine. This new function could be called `update_package_object` to make the intent more clear and it could work pretty close to how you've written it up. Though you can skip the call to `publish_update` and just, internally, do `update_object`, followed by `update_resource_map`.

Are you interested in coding this up? I think we'd happily accept that in either package.

**Comment by isteves** [comment]
Sure!  I'll try it out here first (since I've got a better handle on the structure/work flow here) and if you think it's appropriate to move it, we can do that.

**Comment by amoeba** [comment]
I'm cool with you developing it out anywhere so 👍 .

Since it uses arcticdatautils functions for its work, I'd like to see it go over there at some point but we can talk about it later.

**Comment by isteves** [comment]
First version of `update_package_object` is in datamgmt!  It updates a data object, re-makes the resource map to include the new object, and updates the EML physical sections.  May move to arcticdatautils sometime in the future, but issue is closed for now.
