### ISSUE TITLE
Add package dependencies 

### ISSUE THREAD

**Issue by dmullen17** [NCEAS/datamgmt#49]
Add dependencies on an install of the datamgmt package.  
We currently need: arcticdatautils, dataone, shiny, rhandsontable, any others?

**Comment by isteves** [comment]
depends (loads & attaches): arcticdatautils, dataone, EML
imports (loads only): shiny, rhandsontable, testthat (?), tidyverse (stringr, lubridate)

http://r-pkgs.had.co.nz/namespace.html

**Comment by dmullen17** [comment]
Finished with Travis CI addition
