### ISSUE TITLE
write check_attributes function 

### ISSUE THREAD

**Issue by dmullen17** [NCEAS/datamgmt#80]
High level function for checking whether attribute metadata is correct.  
Should be able to input an eml, a single eml attribute list, or a data.frame.

**Comment by isteves** [comment]
Check `qa_attributes` and @maier-m's `check_package` function for overlap! (in case you haven't already)

**Comment by isteves** [comment]
might be able to use/adapt this: `EML:::check_and_complete_attributes(attributes, NULL)`
https://github.com/ropensci/EML/blob/5f0cf5f5b94122de0ea65a59f40274be2912ac4a/R/set_attributes.R

**Comment by dmullen17** [comment]
@smfreund I ran a couple test cases with the function @isteves found and it should work for your function.  So you can just reference it with `EML:::check_and_complete_attributes(attributes,NULL)`.  
Also thanks @isteves !
